---

- name: Deploy common configuration
  hosts: odroids
  become: true

  roles:
    - common
    - users

- name: reboot
  hosts: odroids
  become: true
  tasks:
    - shell: reboot
      async: 0
      poll: 0
      ignore_errors: true
