---

- name: Install ufw
  pacman: name=ufw state=present

- name: Open SSH port
  ufw: port=ssh rule=allow

- name: Enable ufw
  ufw: state=enabled

- name: Enable ufw on boot

- name: Manage systemd services
  systemd:
    daemon_reload: yes
    enabled: ufw
    state: enabled
