---

- name: add users
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    groups: "{{ item.groups|default([]) }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    password: "{{ item.password|default('') }}"
    comment: "{{ item.gecos|default('') }}"
  when: item.name != ansible_user_id
  with_items: "{{ users }}"

- name: Set authorized_keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys

- name: Disable PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication (yes|no)$"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - reload sshd

- name: Allow group wheel to execute sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^(#\s*)?%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - sudo
