---

- name: add users
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    password: "{{ item.password }}"
    comment: "{{ item.gecos }}"
  with_items: "{{ users }}"

- name: Set authorized_keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys

- name: Disable PasswordAuthentication
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^#?PasswordAuthentication (yes|no)$" 
    line: "PasswordAuthentication no" 
    state: present
  notify:
    - reload sshd
